main: com.shanebeestudios.skassist.SkAssist
name: SkAssist
version: '@version@'
description: "A simple Skript addon to help customize your server to the fullest."
api-version: '1.13'
author: ShaneBee
contributors: [People who care for SkBee ❤️]
website: https://github.com/EquipableMC/SkAssist
depend:
    - Skript
loadbefore:
    - SkQuery
commands:
    skassist:
        description: Main SkAssist command
        permission: skassist.command
permissions:
    skassist.admin:
        default: op
        description: Permission to receive error messages
    skassist.command:
        default: op
        description: Permission to use SkAssist's main command
