main: com.shanebeestudios.skbee.SkBee
name: SkWasp
version: '@version@'
description: "A Skript addon for nbt api, expression and events"
api-version: '1.13'
contributors: [ShaneBee, Equipable, Crebs]
website: https://github.com/CrebsTheCoder/SkWasp
depend:
    - Skript
loadbefore:
    - SkQuery
commands:
    skbee:
        description: Main SkBee command
        permission: skbee.command
permissions:
    skbee.admin:
        default: op
        description: Permission to receive error messages
    skbee.command:
        default: op
        description: Permission to use SkBee's main command
